### PR TITLE
Enable extension. Use plugin URL for base XHTML module

### PR DESCRIPTION
**Pull request by drmacro**
Added extension points to make the plugin extensible. Also use the plugin URI for the base XHTML module rather than relative path (if the OT catalog is in your catalog list in Oyxgen it will resolve the URI reference when you're editing).

For completeness should also add a parameter extension point but I'm out of time for now.

### CODE REVIEW

**Comment by shapiy** [comment]
@drmacro I'm sorry for the late response. Which exactly parameter extension point do you mean?

> For completeness should also add a parameter extension point but I'm out of time for now.

**Comment by drmacro** [comment]
I meant an extension point to allow an extending plugin to also define it's own parameters for the XSLT transform.

I actually went ahead and added this extension point after I made the comment you cited.

**Comment by shapiy** [comment]
@drmacro That was the source of my confusion! :-) 
I have merged your pull request manually. I needed to squash the second commit (where the unwanted extension point was removed).
That was a great patch, thanks.

**Comment by drmacro** [comment]
Cool, glad I could help. Should be a really useful plugin going forward.

I don't have bandwidth right now to look at the indexing, but the DITA for Publishers project includes general index item grouping and sorting logic that is independent of the final rendition the index goes into. It's used to produce back-of-the-book indexes for EPUB and HTML outputs. It might be useful as an alternative to using the PDF2 transform. DITA for Publishers provides a general "map-driven processing" framework that gives the final-phase processing complete access to the map when processing topics, which is what you need to produce output that reflects the entire publication structure. I think it's a cleaner approach than PDF2's merge process, which was required with XSLT 1 but not with XSLT 2.

**Comment by shapiy** [comment]
Hi @drmacro, 

We're happy to consider new approaches to implementing the index. The native (PDF2) index code is arguably messy. I was having a hard time trying to grasp it.

However, it would be a major change. Do you think you could create a GitHub issue? In this case, our team will investigate the technical difficulties and decide if we can add the change to the roadmap.

**Pull request closed without merging**
